metadata.format.version = "1.1"

[versions]

velocity="3.4.0"
kotlin="2.3.10"
kotlinx-coroutines="1.10.2"
paper = "1.21.8-R0.1-SNAPSHOT"
r-task = "3.0.2"
plugin-yml = "0.6.0"
sponge-gradle = "2.3.0"
shadow = "9.3.1"

[libraries]

velocity= { group="com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
sponge = { group = "org.spongepowered", name = "spongeapi", version = "17.0.0" }

# kotlinx
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

#Gradle dependencies
plugin-shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
plugin-kotlin =  { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]

# run-task
r-paper = { id = "xyz.jpenilla.run-paper", version.ref = "r-task"}
r-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "r-task"}

pluginyml-paper = {id = "net.minecrell.plugin-yml.paper", version.ref = "plugin-yml"}
sponge-gradle = { id = "org.spongepowered.gradle.plugin", version.ref = "sponge-gradle" }
